rails/match_solutions/config/routes.rb
Rails.application.routes.draw do
  get 'techscreening/hr'

  get 'techscreening/companies'

  get 'techscreening/professionals'

  get 'qlibri/index'
  get 'qlibri/' => 'qlibri#index'
  get 'company/' => 'qlibri#index'

  get 'qlibri/portfolio'

  get 'qlibri/contacts'
  post 'qlibri/contacts' => 'qlibri#contacts', :as => :qlibri_contact

  get 'pages/home', :as => :pages

  get '/not_found', :to => redirect('/404.html'), :as => :not_found

  get 'pages/about'

  get 'pages/contact'

  get 'pages/faq', :as => :faq

  get 'sessions/new'

  get 'users/show', :as => :user_show
  resources :users

  resources :subcontractors

  get 'projects/success' => 'projects#success', :as => :project_success
  resources :projects

  get    'login'   => 'sessions#new', :as => :login
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy', :as => :logout
  get 	 'logout'  => 'sessions#logout'

  root 'pages#home'

end

rails/match_solutions/app/models/qlibri_contact.rb
class QlibriContact < ActiveRecord::Base
	validates :email, :description, :presence => true
end

rails/match_solutions/app/controllers/qlibri_controller.rb
class QlibriController < ApplicationController
  def index
  	@qlibri_contact = QlibriContact.new
  end

  def portfolio
  end

  def contacts
  	@qlibri_contact = QlibriContact.new(contact_params)
	respond_to do |format|
      if @qlibri_contact.save
		ProjectMailer.qlibri_contact_email(@qlibri_contact).deliver
        format.html { render :index } 
		format.js { render action: 'index' }
	  else 
        format.html { render :index }
		format.js { render json: @qlibri_contact.errors, status: :unprocessable_entity }
	  end	 
	 end
  end

  def contact_params
    params.require(:qlibri_contact).permit(:name, :email, :description)
  end
end

rails/match_solutions/app/controllers/techscreening_controller.rb
class TechscreeningController < ApplicationController
  def hr
  end

  def companies
  end

  def professionals
  end
end

rails/match_solutions/app/helpers/qlibri_helper.rb
module QlibriHelper
end

rails/match_solutions/app/helpers/techscreening_helper.rb
module TechscreeningHelper
end

rails/match_solutions/app/helpers/users_helper.rb
module UsersHelper
	def site_admin_emails
		return [ "dimitar.bonev@gmail.com", "dimitar.bonev1@gmail.com", "georgi.p.todorov@gmail.com"]
		#return ["dimitar.bonev@.gmail.com", "dimitar@getqlibri.com"]
	end
end

rails/match_solutions/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Project: Match - Great IT Teams on demand</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body data-spy="scroll">

<!-- ******HEADER****** --> 
    <header id="header" class="header">  
        <div class="container">            
            <h1 class="logo pull-left">
                <a href="/">
                    <span class="logo-title">Project: Match (:beta)</span>
                </a>
            </h1><!--//logo-->              
            <nav id="main-nav" class="main-nav navbar-right" role="navigation">
                <div class="navbar-header">
                    <button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button><!--//nav-toggle-->
                </div><!--//navbar-header-->            
                <div class="navbar-collapse collapse" id="navbar-collapse">
                    <ul class="nav navbar-nav">
						<% if params[:controller] == :pages && params[:action] == :home %>
							<li class="nav-item"><a class="scrollto" href="#about">How it works</a></li>
						<% else %>
							<li class="nav-item"><a href="/pages/home#about">How it works</a></li>
						<% end %>
						<% if @current_user %>
							<li class="nav-item"><%= link_to "Logged in as: " + @current_user.email, user_show_path %></a></li>
							<li class="nav-item"><%= link_to "Logout", logout_path %></a></li>
						<% else %>
							<li class="nav-item"><%= link_to "Login", login_path %> </li>
						<% end %>
                    </ul><!--//nav-->
                </div><!--//navabr-collapse-->
            </nav><!--//main-nav-->
        </div>
    </header><!--//header-->
    
    <%= yield %>    
      
    <!-- ******FOOTER****** --> 
    <footer class="footer">
        <div class="container text-center">
            <small class="copyright">Created with ♥ by Project: Match, <%= DateTime.now.year%>. All rights reserved. Theme lovingly designed by <a href="http://themes.3rdwavemedia.com" target="_blank">Xiaoying Riley</a></small>
        </div><!--//container-->
    </footer><!--//footer-->


<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-57413264-1', 'auto');
  ga('send', 'pageview');

</script>
</body>
</html>

rails/match_solutions/app/views/layouts/qlibri.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Qlibri: We ♥ Software. Web, Mobile, Desktop and Enterprise development</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body data-spy="scroll">

<!-- ******HEADER****** --> 
    <header id="header" class="header">  
        <div class="container">            
            <h1 class="logo pull-left">
                <a href="/company">
                    <span class="logo-title">ProjectMatch: We ♥ Software</span>
                </a>
            </h1><!--//logo-->              
            <nav id="main-nav" class="main-nav navbar-right" role="navigation">
                <div class="navbar-header">
                    <button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button><!--//nav-toggle-->
                </div><!--//navbar-header-->            
                <div class="navbar-collapse collapse" id="navbar-collapse">
                    <ul class="nav navbar-nav">
						<li class="nav-item"><a href="#about">About</a></li>
						<li class="nav-item"><a href="#portfolio">Portfolio</a></li>
						<li class="nav-item"><a href="#contact">Contact</a></li>
                    </ul><!--//nav-->
                </div><!--//navabr-collapse-->
            </nav><!--//main-nav-->
        </div>
    </header><!--//header-->
    
    <%= yield %>    
      
    <!-- ******FOOTER****** --> 
    <footer class="footer">
        <div class="container text-center">
            <small class="copyright">Created with ♥ by ProjectMatch, <%= DateTime.now.year%>. All rights reserved. Theme lovingly designed by <a href="http://themes.3rdwavemedia.com" target="_blank">Xiaoying Riley</a></small>
        </div><!--//container-->
    </footer><!--//footer-->


<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-57413264-1', 'auto');
  ga('send', 'pageview');

</script>
</body>
</html>

rails/match_solutions/app/views/layouts/techscreening.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Project: Match - Great IT Teams on demand</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body data-spy="scroll">

<!-- ******HEADER****** --> 
    <header id="header" class="header">  
        <div class="container">            
            <h1 class="logo pull-left">
                <a href="/">
                    <span class="logo-title">Project: Match</span>
                </a>
            </h1><!--//logo-->              
            <nav id="main-nav" class="main-nav navbar-right" role="navigation">
                <div class="navbar-header">
                    <button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button><!--//nav-toggle-->
                </div><!--//navbar-header-->            
                <div class="navbar-collapse collapse" id="navbar-collapse">
                    <ul class="nav navbar-nav">
						<li class="nav-item"><a href="#about">How it works</a></li>
						<li class="nav-item"><a href="#why_us">Why us</a></li>
						<li class="nav-item"><a href="#pricing">Pricing</a></li>
						<li class="nav-item"><a href="#contact">Get Started</a></li>
                    </ul><!--//nav-->
                </div><!--//navabr-collapse-->
            </nav><!--//main-nav-->
        </div>
    </header><!--//header-->
    
    <%= yield %>    
      
    <!-- ******FOOTER****** --> 
    <footer class="footer">
        <div class="container text-center">
            <small class="copyright">Created with ♥ by Project: Match, <%= DateTime.now.year%>. All rights reserved. Theme lovingly designed by <a href="http://themes.3rdwavemedia.com" target="_blank">Xiaoying Riley</a></small>
        </div><!--//container-->
    </footer><!--//footer-->


<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-57413264-1', 'auto');
  ga('send', 'pageview');

</script>
</body>
</html>

rails/match_solutions/app/views/pages/home.html.erb
<!-- ******PROMO****** -->
    <section id="promo" class="promo section offset-header">
        <div class="container text-center">
            <h2 class="title" id="title" name="title">Need<br/><span id="title_part">Contractors?</span></h2>
            <p class="intro">Great IT teams and professionals on demand.</p>
            <p class="intro">No bidding. No waiting. No hassle.</p>
			<br />
            <p class="intro">#iOS #web #android #design #enterprise</p>
            <div class="btns">
				<%= link_to "Find a Contractor Now", {:controller => :projects, :action => :new}, {:class => "btn btn-cta-secondary"} %>
            </div>
			<br />
            <br />
            <br />
			<br/>
			Are you a great developer, admin or designer or part of an amazing team?<br/><%= link_to "Apply here to get projects", {:controller => :subcontractors, :action => :new}, {:class => "lnk"} %>
            
            <ul class="meta list-inline">
                
            </ul><!--//meta-->
        </div><!--//container-->          
    </section><!--//promo-->    

    <!-- ******LICENSE****** --> 
    <section id="about" class="license section">
        <div class="container">
            <div class="license-inner">
            <h2 class="title text-center">How it works</h2>
                <div class="info">
					<h4>You need a team or contractor to get a job done?</h4>
					<ul>
						<li><%= link_to "Tell us", { :controller => :projects, :action => :new} %> what needs to be done (e.g. "a social iPhone app", "a web-based document management system")</li>
						<li>We hand-pick up to three pre-vetted teams or professionals who can do what you need and send you an email with information about them</li>
						<li>Chose who you want to talk to and we introduce you</li>
						<li>Start talking directly with the experts</li>
					</ul>
                </div><!--//info-->
                <div class="info">
					<h4>What is it ideal for?</h4>
					<ul>
						<li>Technical realisation or evaluation of an idea (now you can start building that great project)</li>
						<li>Outsourcing projects or parts of projects</li>
						<li>Outsourcing IT services like administration and support</li>
						<li>Finding subcontractors</li>
					</ul>
					<p>You can <strong>start talking</strong> to a real professional or a team <strong>in minutes</strong>. No time-consuming registrations or setup. You simply discuss privately with real experts, using the tools you prefer (email, Skype, IM).</p>
                </div><!--//info-->
                <div class="info">
					<h4>How much does it cost?</h4>
					<p>We are free for the time of the beta. Hurry up!</p>
				</div>
                <div class="cta-container">
                    <div class="speech-bubble">                    
                        <p class="intro text-center">Find a team now. It is free for the time of the beta.</p>
                    </div><!--//speech-bubble-->
                    <div class="btn-container  text-center">
                        
						<%= link_to "Start talking to a team now", {:controller => :projects, :action => :new}, {:class => "btn btn-cta-secondary"} %>
                    </div><!--//btn-container-->
                </div><!--//cta-container-->

            </div><!--//license-inner-->
        </div><!--//container-->
    </section><!--//how-->
<script>
	var titles = ["Designers? ", "Subcontractors?", "Developers?", "IT Experts?", "Contractors? ", "Administrators?", "Consultants? "];
	var i = 0;
	setTimeout(function() { developer(titles[i++]) }, 4000)
	var ts = Date.now();
	
	function developer(what){
		var now = Date.now();
		if (now - ts < 3900){
			return;
		}
		var current_title = titles[i];
		$("#title_part").css('background-color', '#B3C1FF');
		$("#title_part").css('color', 'white');
		for(ii = current_title.length; ii > 0; ii--){
			//current_title = titles[i].substring(0, ii);
			var iii = titles[i].length - ii;
			setTimeout(function(ii) { 
				$("#title_part").css('background-color', 'transparent'); 
				$("#title_part").css('color', '#074f66');
				$("#title_part").html(titles[i].substring(0, ii)); /*alert(titles[i].substring(0, ii) + " " + ii); */
			}, 300, ii);
		}
		increment();

		var title = titles[i];
		current_title = title;
		for(ii = 0; ii <= title.length; ii++){
			var iii = ii;
			//alert(current_title.length);
			setTimeout(function(ii) { 
				var cursor = ii % 2 == 0 ? "|" : "";
				$("#title_part").html(titles[i].substring(0, ii) + cursor); /*alert(titles[i].substring(0, ii) + " " + ii); */
			 }, iii * 40 + 600, ii);
		}

//		var title = titles[i++];
//		$("#title_part").fadeOut('quick', function() { $("#title_part").html(what + "?");});
//		$("#title_part").fadeIn('slow')
		
		ts = Date.now();
		setTimeout(function() { developer(title); }, 4000);
	}
	function increment(){
		i++

		if (i >= titles.length){
			i = 0;
		}
	}
</script>

rails/match_solutions/app/views/qlibri/index.html.erb
<!-- ******PROMO****** -->
<section id="promo" class="promo section offset-header">
	<div class="container text-center">
		<h2 class="title" id="title" name="title">We create products people love</h2>
		<p class="intro">A young development studio</p>
		<p class="intro">creating amazing software products for </p>
		<p class="intro">#iOS #Android #Web #Desktop</p>
		<div class="btns">
			<a href="#contact" class= "btn btn-cta-secondary">Get a Free Quote For Your Project Now</a>
		</div>
		<br />
		<br />
		<br />
		<br/>
		<br />
		<br/>
		<br />
		<br/>
	</div><!--//container-->          
</section><!--//promo-->    

<!-- ******LICENSE****** --> 
<section class="about section">
	<div class="container">
		<a class="anchor" id="about"></a>
		<div class="item col-md-4 col-sm-6 col-xs-12">
		<h2 class="title text-center">Who are we?</h2>
			<div class="info">
				<p>We are a small team of experienced software developers, based in Sofia, Bulgaria.</p> 
				<h4>We love what we do...</h4>
				<p>We simply love software development. We have been doing this since we were kids. Serioulsy, we can't imagine we would do something else.</p>
				<h4>...so we do what we love</h4>
				<p>This is why we started Qlibri.<br/>
				At Qlibri, development is not simply a job. It's a passion and a way of living.
				</p>
			</div><!--//info-->

		</div>
		<div class="item col-md-4 col-sm-6 col-xs-12">
		<a class="anchor" id="portfolio"></a>
		<h2 class="title text-center">What we have done?</h2>
			<div class="info">
				<h4>Some recent projects we are proud of</h4>
				<p>We are absolutely passionate about all of our projects. Here are some of the amazing products the developers of our team have done:</p>
				<ul>
					<li><a href="http://giveapizza.com" target="_blank">Give a Pizza</a></li>
					<li><a href="http://getqlibri.com" target="_blank">Qlibri</a></li>
					<li><a href="http://mytriply.com">Triply</a></li>
					<li><a href="http://meerkapp.com">Meerkapp</a></li>
					<li><a href="http://shtipkasol.com">Pinch of Salt</a></li>
				</ul>
				<p>Our team has long experience in building various software solutions ranging from mission-critical large-scale systems for financial and insurance companies, to fun mobile apps.</p>
			</div><!--//info-->

		</div>
		<div class="item col-md-4 col-sm-6 col-xs-12">
		<h2 class="title text-center">What can we do?</h2>
			<div class="info">
				<h4>Bring your ideas to life</h4>
				<p>You have a project or just a great idea? Now you can start building it. If it's software, we can make it.</p>
				<ul>
					<li>Website</li>
					<li>Mobile App</li>
					<li>Specialized software for your company</li>
				</ul>
				<p>Our team has long experience in building various software solutions ranging from mission-critical large-scale systems for financial and insurance companies, to fun mobile apps.</p>
			</div><!--//info-->
			<!--//info-->
			<!--//cta-container-->

		</div><!--//license-inner-->

	</div><!--//container-->

</section><!--//how-->
<section class="license section">
	<div class="container">
		<div class="license-inner">
			<a class="anchor" id="contact"></a>
			<div class="cta-container anchor">
				<h2 class="title text-center">Contact us</h2>
				<div class="speech-bubble">                    
					<p class="intro text-center">Talk to us now. You will be on a mail / skype / hangouts chat with one of our developers in a few minutes. No obligations or commitments.</p>
				</div><!--//speech-bubble-->
				<div class="btn-container text-center">
					
					We love email. Drop us a few lines about what needs to be done at <a href="mailto:contact@getqlibri.com">contact@getqlibri.com </a> and we will be happy to discuss!
					<%= render 'contact_form' %>
				</div><!--//btn-container-->
				<br/>
				<br/>
				<br/>
			</div><!--//cta-container-->
		</div>
	</div>
</section>
<script>
$('#contact_form').on('ajax:success', function(event, data, status, xhr) {
	alert('success');
});
$('#contact_form').on('ajax:error', function(event, data, status, xhr) {
	alert('error');
});
</script>

rails/match_solutions/app/views/techscreening/companies.html.erb
<h1>Techscreening#companies</h1>
<p>Find me in app/views/techscreening/companies.html.erb</p>

rails/match_solutions/app/views/techscreening/hr.html.erb
<!-- ******PROMO****** -->
<section id="promo" class="promo section offset-header">
	<div class="container text-center">
		<h2 class="title" id="title" name="title"><span class="highlight">Technical</span> Screening Services</h2>
		<p class="intro">We screen technical candidates before you spend time and effort on them.</p>
		<hr/>
		<ul class="text-left" >
			<li class="intro">Save time and money</li>
			<li class="intro">Specifically tailored for HR companies</li>
			<li class="intro">Send better and more qualified candidates to your clients</li>
		</ul>
		<div class="btns">
			<a href="#contact" class= "btn btn-cta-secondary">Get Started Now. The First Candidate is Free.</a>
		</div>
		<br />
		<br />
		<br />
		<br/>
		<br />
		<br/>
		<br />
		<br/>
	</div><!--//container-->          
</section><!--//promo-->    

<section class="about section">
	<div class="container">
		<a class="anchor" id="about"></a>
		<div class="item col-md-12 col-sm-6 col-xs-12">
		<h2 class="title text-center">How it Works?</h2>
			<p class="intro">We have a very simple, streamlined process using tools you already know and love like email, Skype, Google Docs and Hangouts</p>
			<div class="row">
				<div class="item col-md-4 col-sm-6 col-xs-12">
					<div class="icon-holder">
                        <i class="fa fa-heart"></i>
                    </div>
					<div class="content">
						<h3 class="sub-title">1. Send us the candidate CV and the position requirements</h3>
						<p>
						<a href="#contact">Send us</a> information about the candidate (ideally his or her CV) and tell us what the requirements for that position are.
						</p>
					</div>
				</div>
				<div class="item col-md-4 col-sm-6 col-xs-12">
					<div class="icon-holder">
                        <i class="fa fa-heart"></i>
                    </div>

					<div class="content">
						<h3 class="sub-title">2. We interview the candidate</h3>
						<p>
						We will setup a Skype, Phone or Google Hangouts interview with the candidate.
						During this 20 ~ 45 minutes interview, we asses the candidate skills and qualifications for that position.
						</p>
					</div>
				</div>
				<div class="item col-md-4 col-sm-6 col-xs-12">
					<div class="icon-holder">
                        <i class="fa fa-heart"></i>
                    </div>

					<div class="content">
						<h3 class="sub-title">3. We provide you with a simple Green / Red report</h3>
						<p>
						Simple, yet comprehensive, the report will let you know how the candidate qualifies for the position at hand.
						</p>
					</div>
				</div>

			</div>
			<div class="row">
				<div class="btns text-center">
					<a href="#contact" class= "btn btn-cta-primary">Get Started Now. The First Candidate is Free.</a>
				</div>
			</div>
			<!--//info-->
		</div>
</section>

<section class="features section">
	<div class="container text-center">
		<a class="anchor" id="why_us"></a>
		<div class="item col-md-12 col-sm-6 col-xs-12">
			<h2 class="title text-center">Why use us?</h2>
			<p style="font-size:large">You save time and money</p>
			<p style="font-size:large">You send more qualified candidates to your clients</p>
			<p style="font-size:large">Your clients are more satisfied</p>
		</div>
</section>
<section class="about section">
	<div class="container">
		<a class="anchor" id="pricing"></a>
		<div class="item col-md-12 col-sm-6 col-xs-12">
			<h2 class="title text-center">Pricing</h2>
			<p class="intro">Your first candidate screening interview is free. If you are happy with our services (and we are sure you will be), we charge $20 for a quick 20-minutes interview and $35 for a more elaborate 45-minutes interview.</p>
		</div>
	</div>
</section>
<section class="features section">
	<div class="container text-center">
		<a class="anchor" id="contact"></a>
		<div class="item col-md-12 col-sm-6 col-xs-12">
			<h2 class="title text-center">Get Started</h2>
			<p class="intro" style="font-size:large">We love email. Simply <a href="mailto:contact@getqlibri.com">drop us a line at contact@getqlibri.com</a> to get in touch and we will contact you as soon as we can.</p>
		</div>
</section>

rails/match_solutions/app/views/techscreening/professionals.html.erb
<h1>Techscreening#professionals</h1>
<p>Find me in app/views/techscreening/professionals.html.erb</p>