rails/two/config/routes.rb
Rails.application.routes.draw do
  resources :quotations

  get 'search/get'
  get 'projects/search'

  resources :projects

  root 'projects#index'

end

rails/two/app/models/project.rb
class Project < ActiveRecord::Base
	validates :title, :description, presence: true
	validates :place, presence: true
	has_many :quotations, dependent: :destroy
end

rails/two/app/models/quotation.rb
class Quotation < ActiveRecord::Base
  belongs_to :project
end

rails/two/app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  def search
  	@search_term = params[:q]
	# we should use parametrized query here
	@projects = Project.where("title like \"%#{@search_term}%\"")
	flash[:notice] = "Found #{@projects.count} projects matching #{@search_term}"
	render :index
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)
	@project.created_at = Time.now
	@project.updated_at = Time.now

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
	@project.updated_at = Time.now
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def search
  	@search_term = params[:q]
	# we should use parametrized query here
	@projects = Project.where("title like \"%#{@search_term}%\" OR description like \"%#{@search_term}%\"")
	render :index
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:title, :description, :place, :allow_remote)
    end
end

rails/two/app/controllers/quotations_controller.rb
class QuotationsController < ApplicationController
  before_action :set_quotation, only: [:show, :edit, :update, :destroy]

  # GET /quotations
  # GET /quotations.json
  def index
    @quotations = Quotation.all
  end

  # GET /quotations/1
  # GET /quotations/1.json
  def show
  end

  # GET /quotations/new
  def new
    @quotation = Quotation.new
  end

  # GET /quotations/1/edit
  def edit
  end

  # POST /quotations
  # POST /quotations.json
  def create
    @quotation = Quotation.new(quotation_params)

    respond_to do |format|
      if @quotation.save
        format.html { redirect_to @quotation, notice: 'Quotation was successfully created.' }
        format.json { render :show, status: :created, location: @quotation }
      else
        format.html { render :new }
        format.json { render json: @quotation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /quotations/1
  # PATCH/PUT /quotations/1.json
  def update
    respond_to do |format|
      if @quotation.update(quotation_params)
        format.html { redirect_to @quotation, notice: 'Quotation was successfully updated.' }
        format.json { render :show, status: :ok, location: @quotation }
      else
        format.html { render :edit }
        format.json { render json: @quotation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /quotations/1
  # DELETE /quotations/1.json
  def destroy
    @quotation.destroy
    respond_to do |format|
      format.html { redirect_to quotations_url, notice: 'Quotation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_quotation
      @quotation = Quotation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def quotation_params
      params.require(:quotation).permit(:project_id, :created_at, :description)
    end
end

rails/two/app/controllers/search_controller.rb
class SearchController < ApplicationController
  def get
  	@search_term = params[:q]
	# we should use parametrized query here
	@projects = Project.where("title like \"%#{@search_term}%\"")
  end
end

rails/two/app/helpers/quotations_helper.rb
module QuotationsHelper
end

rails/two/app/helpers/search_helper.rb
module SearchHelper
end

rails/two/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Two</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<h1>Outsource.Me</h1>
<p>Get a quality contractor company for your project. Find a project for your company.</p>
<%= yield %>

</body>
</html>

rails/two/app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description, :cols => 20, :rows => 10 %>
  </div>
  <div class="field">
    <%= f.label :place %><br>
    <%= f.text_field :place%>
  </div>
  <div class="field">
	<%= f.label :allow_remote do %>
		<%= f.check_box :allow_remote %>
		Allow remote
	<% end %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

rails/two/app/views/projects/index.html.erb
<h1>Listing projects</h1>

<div id="search">
<%= form_tag(url_for(:controller => :projects, :action => :search), method: "get") do %>
  <%= label_tag(:q, "Search for:") %>
  <%= text_field_tag(:q, params[:q]) %>
  <%= submit_tag("Search") %>
<% end %>

<% if @search_term %>
<p>Found <%= @projects.count %> projects containing <%= @search_term %></p>
<% end %>
</div>

<% if @search_term %>
	<div>Found <%= @projects.count %> projects matching <%= @search_term %>. <%= link_to 'Clear Search', :controller => :projects, :action => :index %></div>
<% end %>

<table>
  <thead>
    <tr>
      <th>Posted On</th>
      <th>Title</th>
      <th>Description</th>
      <th>Location</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= project.created_at.strftime("%Y/%m/%d") %></td>
        <td><%= project.title %></td>
        <td><%= sanitize project.description[0..50] %>...</td>
        <td><%= project.place %>
			<% if project.allow_remote %>
				(allows remote)
			<% end %>
		</td>
        <td><%= link_to 'View', project %></td>
        <td><%= link_to 'Edit', edit_project_path(project) %></td>
        <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Project', new_project_path %>

rails/two/app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @project.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @project.description %>
</p>

<%= @project.quotations.count %> applications for this project so far.
<% @project.quotations.each do |q| %>
<p><% q.description %></p>
<% end %>
<%= link_to 'Submit Application', :controller => :quotations, :action => :create %>

<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>

rails/two/app/views/quotations/_form.html.erb
<%= form_for(@quotation) do |f| %>
  <% if @quotation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@quotation.errors.count, "error") %> prohibited this quotation from being saved:</h2>

      <ul>
      <% @quotation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :project_id %><br>
    <%= f.text_field :project_id %>
  </div>
  <div class="field">
    <%= f.label :created_at %><br>
    <%= f.datetime_select :created_at %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

rails/two/app/views/quotations/edit.html.erb
<h1>Editing quotation</h1>

<%= render 'form' %>

<%= link_to 'Show', @quotation %> |
<%= link_to 'Back', quotations_path %>

rails/two/app/views/quotations/index.html.erb
<h1>Listing quotations</h1>

<table>
  <thead>
    <tr>
      <th>Project</th>
      <th>Created at</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @quotations.each do |quotation| %>
      <tr>
        <td><%= quotation.project %></td>
        <td><%= quotation.created_at %></td>
        <td><%= quotation.description %></td>
        <td><%= link_to 'Show', quotation %></td>
        <td><%= link_to 'Edit', edit_quotation_path(quotation) %></td>
        <td><%= link_to 'Destroy', quotation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Quotation', new_quotation_path %>

rails/two/app/views/quotations/new.html.erb
<h1>New quotation</h1>

<%= render 'form' %>

<%= link_to 'Back', quotations_path %>

rails/two/app/views/quotations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Project:</strong>
  <%= @quotation.project %>
</p>

<p>
  <strong>Created at:</strong>
  <%= @quotation.created_at %>
</p>

<p>
  <strong>Description:</strong>
  <%= @quotation.description %>
</p>

<%= link_to 'Edit', edit_quotation_path(@quotation) %> |
<%= link_to 'Back', quotations_path %>

rails/two/app/views/search/get.html.erb
<h1>Search Projects</h1>
<p>Searching projects by search term <%= "#{@search_term}" %></p>
<p>found <%= @projects.count %> projects...
<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Location</th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= project.title %></td>
        <td><%= project.description %></td>
        <td><%= project.place %>
			<% if project.allow_remote %>
				(allows remote)
			<% end %>
		</td>
      </tr>
    <% end %>
  </tbody>
</table>
<p>
<%= link_to "Back", projects_path %>
</p>